[package]
name = "git-cliff-cli"
version = "0.1.0"
description = ""
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
readme = "README.md"
documentation = "https://github.com/orhun/git-cliff/blob/master/README.md"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = []
categories = []
edition = "2018"

[dependencies]
git-cliff-core = { path = "../git-cliff-core" }
pretty_env_logger = "0.4.0"
log = "0.4.14"

[dependencies.structopt]
version = "0.3"
default-features = false
features = ["suggestions", "color", "wrap_help"]
