[workspace]
members = [
    "git-cliff-core",
    "git-cliff",
]

[workspace.dependencies]
regex = "1.6.0"
glob = "0.3.0"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1
strip = true

[profile.bench]
opt-level = 3
debug = false
