[changelog]
header = """
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

body = """
## {{ version | default(value="[unreleased]") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | capitalize}}
{% for commit in commits %}
- {{ commit.message | capitalize }}{% endfor %}
{% endfor %}
"""

footer = ""

group_parsers = [
    { regex = "feat*", group = "Features"},
    { regex = "fix*", group = "Bug Fixes"},
    { regex = "chore*", group = "Miscellaneous Tasks"},
]

filter_group = false
