[changelog]
# changelog header
header = """
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
## {% if version %}[{{ version }}] - {{ date }}{% else %}[unreleased]{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | capitalize}}
{% for commit in commits %}
- {{ commit.message }}{% endfor %}
{% endfor %}
"""

# changelog footer
footer = ""

# regex patterns for grouping commits
group_parsers = [
    { regex = "feat*", group = "Features"},
    { regex = "fix*", group = "Bug Fixes"},
    { regex = "chore*", group = "Miscellaneous Tasks"},
]

# filter out the commits that are not matched by group_parsers
filter_group = false

# glob pattern for matching tags
tag_pattern = "v[0-9]*"

# https://docs.rs/chrono/latest/chrono/format/strftime/index.html
date_format = "%Y-%m-%d"
