[package]
name = "git-cliff-core"
version = "0.8.0" # managed by release.sh
description = "Core library of git-cliff"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
thiserror = "1.0.31"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
tera = "1.16.0"
regex = "1.6.0"
serde_regex = "1.1.0"
indexmap = "1.9.1"
toml = "0.5.9"
glob = "0.3.0"

[dependencies.git2]
version = "0.14.4"
default-features = false

[dependencies.config]
version = "0.13.1"
default-features = false
features = ["toml", "yaml"]

[dependencies.git-conventional]
version = "0.11.3"
features = ["serde"]

[dependencies.rust-embed]
version = "6.4.0"
features = ["debug-embed"]

[dev-dependencies]
pretty_assertions = "1.2.1"
