[package]
name = "git-cliff-core"
version = "0.1.0-rc.16"
description = "Core library of git-cliff"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
categories = ["command-line-utilities"]
edition = "2018"

[dependencies]
thiserror = "1.0"
serde = "1.0"
serde_derive = "1.0"
tera = "1.9.0"
regex = "1.5.4"
serde_regex = "1.1.0"
indexmap = "1.6.2"

[dependencies.git2]
version = "0.13.20"
default-features = false

[dependencies.config]
version = "0.11.0"
default-features = false
features = ["toml", "yaml"]

[dev-dependencies]
pretty_assertions = "0.7"

[dependencies.git-conventional]
version = "0.9.2"
features = ["serde"]
