[package]
name = "git-cliff-core"
version = "0.1.1" # managed by release.sh
description = "Core library of git-cliff"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
edition = "2018"

[dependencies]
thiserror = "1.0.26"
serde = "1.0.27"
serde_derive = "1.0.27"
tera = "1.12.1"
regex = "1.5.4"
serde_regex = "1.1.0"
indexmap = "1.7.0"

[dependencies.git2]
version = "0.13.21"
default-features = false

[dependencies.config]
version = "0.11.0"
default-features = false
features = ["toml", "yaml"]

[dev-dependencies]
pretty_assertions = "0.7"

[dependencies.git-conventional]
version = "0.9.2"
features = ["serde"]
