[package]
name = "git-cliff-core"
version = "1.0.17" # managed by release.sh
description = "Core library of git-cliff"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
edition = "2021"
rust-version = "1.60.0"

[dependencies]
glob.workspace = true
regex.workspace = true
thiserror = "1.0.37"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"
tera = "1.17.1"
serde_regex = "1.1.0"
indexmap = "1.9.2"
toml = "0.5.9"
lazy-regex = "2.3.1"

[dependencies.git2]
version = "0.15.0"
default-features = false

[dependencies.config]
version = "0.13.2"
default-features = false
features = ["toml", "yaml"]

[dependencies.git-conventional]
version = "0.12.1"
features = ["serde"]

[dependencies.rust-embed]
version = "6.4.2"
features = ["debug-embed"]

[dev-dependencies]
pretty_assertions = "1.3.0"
