[package]
name = "git-cliff-core"
version = "0.6.1" # managed by release.sh
description = "Core library of git-cliff"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
edition = "2021"

[dependencies]
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"] }
tera = "1.15.0"
regex = "1.5.5"
serde_regex = "1.1.0"
indexmap = "1.8.0"
toml = "0.5.8"
glob = "0.3.0"

[dependencies.git2]
version = "0.14.2"
default-features = false

[dependencies.config]
version = "0.12.0"
default-features = false
features = ["toml", "yaml"]

[dependencies.git-conventional]
version = "0.11.2"
features = ["serde"]

[dependencies.rust-embed]
version = "6.3.0"
features = ["debug-embed"]

[dev-dependencies]
pretty_assertions = "1.2.0"
