[package]
name = "git-cliff-core"
version = "0.2.6" # managed by release.sh
description = "Core library of git-cliff"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
edition = "2018"

[dependencies]
thiserror = "1.0.28"
serde = "1.0.130"
serde_derive = "1.0.130"
tera = "1.12.1"
regex = "1.5.4"
serde_regex = "1.1.0"
indexmap = "1.7.0"
toml = "0.5.8"

[dependencies.git2]
version = "0.13.21"
default-features = false

[dependencies.config]
version = "0.11.0"
default-features = false
features = ["toml", "yaml"]

[dependencies.git-conventional]
version = "0.10.1"
features = ["serde"]

[dependencies.rust-embed]
version = "6.2.0"
features = ["debug-embed"]

[dev-dependencies]
pretty_assertions = "0.7"
